### ISSUE TITLE
Reporting overhaul

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1076]
The reporting features we have offered in AffiliateWP have suffered since day one. We have numerous issues open that discuss various aspects of reports and where they could be improved. To make the process easier, we're consolidating them all into this issue. Here we will create one master plan for the reporting overhaul in version 1.8.

Note: it is *very* likely that we will do this in a non-backwards compatible way that will have the potential for breaking custom integrations with the report pages (if any exist). We have decided that this is necessary in order to really fix what we should have done right from the beginning.

The following issues are getting closed in favor of this: #616 #848 #970.

We will be working out the exact plan of attack in the next few days/weeks and will present the finalized plan here before building it.

**Comment by pippinsplugins** [comment]
Here are some of the features / report views we'd like to achieve:

Affiliates
	- Affiliates registered over X timeframe
	- Affiliates that have sent traffic (visits) in X timeframe
		- just converted visits
		- non-converted visits
	- Affiliates that earned $x.xx - $x.xx in X timeframe
	- Affiliates that earned $x.xx in y period over X timeframe (ex: $100 per month in 2015)
	- Earnings mix of affiliates (ex. John Doe accounts for 80% of earnings)
	- Affiliate earnings over X timeframe


Referrals
	- Best dates by performance
	- Highest referred products
	- Highest/lowest earning affiliates
	- Best conversion rates by product
	- Best product categories
	- 

Visits
	- Best / worst landing pages
	- Conversion rates over X timeframe
	- Conversion rates by affiliate
	- Number of visits over X timeframe 

Campaigns
	- Best / worst converting campaigns
	- Best / worst campaigns by affiliate


Global filters / features for all reports:

	- Include/exclude affiliates
	- Start date
	- End date
	- Status
	- All report views can be exported to a CSV

**Comment by pippinsplugins** [comment]
These could be done through a combination of graphs and table data.

An example of how we'd like the graphs to look:
 
![WooCommerce Graphs](https://cloud.githubusercontent.com/assets/6686642/9995075/3caabbf4-604e-11e5-84d6-a6f87d767f91.png)

Also thinking that we will adjust the tabs at the top to:
- Earnings
- Visits
- Campaigns
- Registrations

**Comment by worldtravlr** [comment]
Here are some charts from a previous plugin we used that had a Total Area which would cover seeing all results for a certain time period and/or all time and could be sorted by commission total as we'll as any other main column.

![screen shot 2016-01-26 at 1 05 35 pm](https://cloud.githubusercontent.com/assets/6686642/12593407/326921d2-c42e-11e5-94d4-ef77e0289801.jpg)

There is also the main Affiliate Plugin Area that shows graphs and charts in a nice manner and can be filtered as desired.

![screen shot 2016-01-26 at 1 06 27 pm](https://cloud.githubusercontent.com/assets/6686642/12593429/50865c34-c42e-11e5-926a-0c9b6049abe9.jpg)

Hope that helps and excited to see how this progresses.

**Comment by pippinsplugins** [comment]
Thanks!

**Comment by michaelbeil** [comment]
> It shows dots for every earning, and connects every single earning. That may be good for the today/yesterday filter but isn't good for the weekly/monthly/quarterly/yearly filter, as they appear as vertical lines. 

> It would be much better for the weekly and monthly filter to summate the single earnings of each day and only connect the results of each day. For the quarterly and yearly filter it would be best to summate the earnings of each week and connect them. 

https://secure.helpscout.net/conversation/166070811/26699/?folderId=205524

**Comment by worldtravlr** [comment]
Just wanted to check back on this and see if there is any progress or anything I can help test :-)

**Comment by pippinsplugins** [comment]
We're still working on it. Not too much to show yet.

**Comment by michaelbeil** [comment]
Adding total products purchased through affiliates to the above list:
- a list of products (with quantity sold) sold through affiliates

**Comment by worldtravlr** [comment]
One idea related to that @michaelbeil is an option to have all non-affiliate purchases attributed to a "Direct" affiliate as a fixed or customized amount.  This way if for instance the store makes 5% on affiliate purchases and 10% of direct purchases, they can easily check Direct affiliate to see their profit for that range, etc.

**Comment by wordmaid** [comment]
Following on from our recent discussion on adding filters, it would be useful to be able to also filter the Landing Pages on the Visits page - admins may want to be able to filter to see a specific page and how that has been performing overall (without seeing all the other pages as well).

Also, thoughts on adding an Order ID/Reference field next to converted visits? And linking the Referral ID to the actual referral? Both already exist in the Referrals screen - but it would be handy to be able to access this information from the Visits screen as well.

**Comment by wordmaid** [comment]
Additionally, the Referral ID should also show in the Referrals screen in its own column (should maybe be the first column?).

**Comment by pippinsplugins** [comment]
I would _love_ to be able to see all referrals generated for a specific landing page. Leads us into an area where we can start offering comparisons so site admins can see and compare the performance of different landing pages.

**Comment by ramiabraham** [comment]
Branch [issue/1076](https://github.com/AffiliateWP/AffiliateWP/tree/issue/1076) contains a variety of base components relating to the reporting overhaul.

_*Many components are unfinished, please consider items a WIP._



### Tabs:

Tab content is adjusted so that the tabs now present are:

- Overview
- Affiliates
- Referrals
- Visits
- Campaigns

### Meta boxes

[More info about affwp meta boxes can be found here](https://github.com/AffiliateWP/AffiliateWP/issues/1225#issuecomment-214877868).

### Exporter and related list tables

#### Export class

The `Affiliate_WP_Reports_Export` is extended from the primary `Affiliate_WP_Export` class.

This serves as a _base_ for reports exports. In progress are classes which further extend this (instead of each directly extending `Affiliate_WP_Export`. This is to allow for integration of exporter options.

Each view in the Reports section will contain an **Export to CSV** feature (a start on this is located in `Affiliate_WP_Reports_Export->display()`). This can be seen in the below screenshot.

Note: An alternative route is to define a method in the `Affiliate_WP_Export` class to allow for sending data to a currently-displayed `WP_List_Table`.

### Views

The table nav filters define extra filters to filter the list table data shown. Presently, the affiliates tab contains these fields, via the `AffWP_Export_Reports_List_Table->advanced_filters()` method:

![List table filters example](http://i.imgur.com/rPjgTRD.png "List table filters example")

#### List tables

The `AffWP_Export_Reports_List_Table` class defines a base for reports list table views. The `affiliates` tab of reports presently displays this table. The referrals, visits, and campaigns tabs will also contain their own list table, extended from `AffWP_Export_Reports_List_Table`.

The advanced_filters method within the list table class renders additional search fields, and an associated action.

#### Graphs

Graphs have been adjusted visually to include more data on the overview page, and some minor styling elements.

- A translucent background to graph data better displays relationships between data sets:
![graph](http://i.imgur.com/iFvFWRm.png "graph")

- Affiliate registration is now shown, in addition to campaign, reference, and context data planned.

#### File structure changes:

- Graphs are now located in `includes/admin/graphs`, with the base class remaining in `includes/class-graph` for front-end usage compatibility.

#### Questions
- Should graphs be above meta box data on any page?
- What other style adjustments are desired for graphs?
- What additional data should be displayed? One option is to unify data between list tables _and_ any graph appearing on that page, so that any time the list table or graph is filtered, the other is, as well. A later enhancement not ideal for 1.8, probably.

**Comment by pippinsplugins** [comment]
This is looking really good!

>>>Should graphs be above meta box data on any page?

I don't think so. I'd vote for below.

>>>What other style adjustments are desired for graphs?

This is a good start. I may have more changes I'd like to see after I play with it more in a site that has real data.

>>>What additional data should be displayed? One option is to unify data between list tables and any graph appearing on that page, so that any time the list table or graph is filtered, the other is, as well. A later enhancement not ideal for 1.8, probably.

I'd definitely love to see graphs and table data be synced at some point, though you're probably right about that being outside of scope for 1.8.

**Comment by pippinsplugins** [comment]
A few items I'm seeing that are marking testing cumbersome (with debug on);

( ! ) Strict standards: Declaration of Affiliate_WP_Reports_Export::get_data() should be compatible with Affiliate_WP_Export::get_data() in /Users/pippinwilliamson/Sites/trunk/wp-content/plugins/affiliate-wp/includes/admin/tools/export/class-export-reports.php on line 120

Notice: Undefined variable: reg_start_date in /Users/pippinwilliamson/Sites/trunk/wp-content/plugins/affiliate-wp/includes/admin/reports/class-export-reports-list-table.php on line 136

Notice: Undefined variable: reg_end_date in /Users/pippinwilliamson/Sites/trunk/wp-content/plugins/affiliate-wp/includes/admin/reports/class-export-reports-list-table.php on line 138

Notice: Undefined variable: earnings_start_date in /Users/pippinwilliamson/Sites/trunk/wp-content/plugins/affiliate-wp/includes/admin/reports/class-export-reports-list-table.php on line 145

Notice: Undefined variable: earnings_end_date in /Users/pippinwilliamson/Sites/trunk/wp-content/plugins/affiliate-wp/includes/admin/reports/class-export-reports-list-table.php on line 147 

Could you get those fixed for further testing?

**Comment by ramiabraham** [comment]
💃  fixed on issue/1076 branch

**Comment by worldtravlr** [comment]
Love all the updated reporting options!  Awesome work and this should be really helpful for both store owners as well as for affiliates.

Sadly, the graphs don't seem to solve any of our partner frustrations currently as they still show just a ton of indiscernible dots at high volume.  I think a fix to this would be to either by default show, or add the option of showing daily totals instead of individual sales/conversions.  I would recommend daily totals be default and maybe smaller volume partner could switch to the dot view if desired.

![screen shot 2016-04-28 at 10 11 19 am](https://cloud.githubusercontent.com/assets/6686642/14872692/c03f975e-0d29-11e6-93c9-806a3b76908b.jpg)
![screen shot 2016-04-28 at 10 10 42 am](https://cloud.githubusercontent.com/assets/6686642/14872691/c03de058-0d29-11e6-90a0-1184da87eb19.jpg)
![Uploading Screen Shot 2016-04-28 at 10.09.27 AM.jpg…]()
![screen shot 2016-04-28 at 10 08 36 am](https://cloud.githubusercontent.com/assets/6686642/14872690/c039ff9c-0d29-11e6-8dae-9594d41033d8.jpg)
![screen shot 2016-04-28 at 10 07 53 am](https://cloud.githubusercontent.com/assets/6686642/14872689/c0393ae4-0d29-11e6-9ab3-d5a00584c80a.jpg)

**Comment by pippinsplugins** [comment]
@worldtravlr Thank you for the feedback. We're still making improvements and definitely aren't done yet :)

@ramiabraham In the `was_affiliate_registered_between()` method of `AffWP_Export_Reports_List_Table`, there is an undefined variable `$registered`.

**Comment by pippinsplugins** [comment]
When filtering the affiliates report, I'm getting a whitescreen. No errors present.

**Comment by ramiabraham** [comment]
Yup my bad, committed unfinished stuff. `advanced_filters()` and `was_affiliate_registered_between()` methods to be completed soon.

**Comment by worldtravlr** [comment]
Well awesome work @ramiabraham and the team!  Already reporting is much more robust and excited to see all the improvements as they develop!

**Comment by pippinsplugins** [comment]
We're making a lot of progress here but it's become apparent that it's much more than a two week, or even four week project. We're getting closer but aren't there yet and we don't want to put it in core until it's completely ready, so with that we've decided to go ahead and bump this to 1.9.

**Comment by worldtravlr** [comment]
Looking forward to seeing the final product in 1.9 :-)

**Comment by worldtravlr** [comment]
Any beta updates that need testing here?  Is there any chance this might be ready by September for final testing?

**Comment by michaelbeil** [comment]
Everything is in branch `issue/1076` right now if you care to test. We are shooting for a release by the end of the month.

**Comment by pippinsplugins** [comment]
Note: what is in 1076 is not likely remotely final. We've had a meeting today to discuss general direction and there should be a lot of progress in the next week or so that dramatically changes what is there now.

**Comment by worldtravlr** [comment]
Awesome!  That is exciting.  Let me know when the changes are done and glad to do some review and testing.

**Comment by ramiabraham** [comment]
Closing in favor of #1525
