### ISSUE TITLE
Errors when saving settings + the license key can't be removed

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1894]
These 2 issues are linked together. Tested with AffiliateWP 1.9.8 latest master (also tested with 1.9.7)

Firstly, if you try and save the AffiliateWP settings, and you don't have a license key entered, it throws some errors and the settings cannot be saved.

The URL becomes `/wp-admin/admin.php?page=affiliate-wp-settings&affwp_notice=license-&affwp_success=no` which is related to the lines mentioned below.

```
PHP Notice:  Trying to get property of non-object in /wp-content/plugins/affiliatewp/includes/admin/settings/class-settings.php on line 1189
```

```
PHP Notice:  Trying to get property of non-object in /wp-content/plugins/affiliatewp/includes/admin/settings/class-settings.php on line 1191
```

https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/admin/settings/class-settings.php#L1189-L1191

I replicated this on 3 machines.

You may not see any errors at first. If not, try this:

1. Delete your `affwp_settings` options row in the DB
2. Visit the affwp settings page, try and change a value and save the settings
3. Check error log

If you still don't see anything, try changing another setting and save.

___

The second issue is if you do have a license key already activated, you can't fully remove it. I believe I've seen this recently in support.

To replicate:

1. Click to deactivate license
2. Remove license key from input field
3. Save settings
4. The license key remains.

This sounds like it will be fixed when the first issue is fixed.

@AffiliateWP/core can anyone else replicate? I know @wordmaid can.

**Comment by DrewAPicture** [comment]
Essentially what's happening here is a called a race condition, albeit a very slow race condition. Basically. the way `get_license_key()` is geared currently, if `$key` is empty, the `else` condition fires, which pulls the already-saved license key value regardless of what was passed. Basically, while attempting to save the empty field, the already-saved field value is being used. Classic race condition

Started a PR that should fix the inability to remove the key. I'm working on tests, but running into some pollution problems related to defining constants within the test framework ;)

PR: #1895

**Comment by pippinsplugins** [comment]
@sumobi could you test this please?

**Comment by DrewAPicture** [comment]
Added unit tests.

**Comment by sumobi** [comment]
To test I deleted my settings row to start fresh. It took 3 tries to activate the key. Each time it reloaded the page and the license key field was blank. The 3rd try worked. I've seen this in support numerous times.

I still cannot remove the key completely. It's still there if I deactivate the key, remove the key, and save the settings.

**Comment by pippinsplugins** [comment]
@DrewAPicture could you re-review this today?

**Comment by sumobi** [comment]
Any luck with this @DrewAPicture?

**Comment by DrewAPicture** [comment]
@sumobi Can you please walk me through your testing routine again? The problems with activation should probably be discounted since that involves remote calls and isn't directly related to saving.

**Comment by DrewAPicture** [comment]
@sumobi Turns out, I was very much mistaken in that activation/deactivation was _very much_ tied to saving. I've pushed some changes to the PR that will hopefully have positive results in your testing.

It's worth noting that I've made one important adjustment to the flow of changing the license key value – if the license has been activated, the field is now set to read only.

So if you don't have a global license key set via the constant, and the license has been activated, you have to click "Deactivate License` to change the value. The contextual help text displayed below the field attempts to make this behavior clear in the various contexts.

**Comment by sumobi** [comment]
@DrewAPicture I like that approach. It's working well for me, I haven't seen any issues with not being able to deactivate it, the license key sticking or trying to activate it multiple times  👍

**Comment by DrewAPicture** [comment]
Awesome, good to hear it :)

**Comment by DrewAPicture** [comment]
Merged #1895.
